cover:
  cache: disk
  cache: /mnt/warez/.cover_cache

paths:
  inbox: /mnt/warez/abooksinbox
  stage: /mnt/warez/_am_stage
  output: /mnt/warez/abooks_ready
  archive: /mnt/warez/abooks
  cache: /mnt/warez/am_cache

behavior:
  clean_stage_on_start: true
  clean_stage_on_success: true
  prompts_enabled: true

audio:
  ffmpeg_loglevel: error
  loudnorm: false
