services:
  audiomason:
    build: .
    image: audiomason:dev
    user: "${UID}:${GID}"
    volumes:
      - /mnt/warez:/mnt/warez
      - /etc/audiomason:/etc/audiomason:ro
    environment:
      - TZ=Europe/Bratislava
      - AUDIOMASON_CONFIG=/etc/audiomason/config.yaml
